Fix rake errors
Fix 'NoMethodError: undefined method `last_comment'' errors when trying
to run rake for this gem. Rake 11.0.1 removes the last_comment method
which rspec-core (< 3.4.4) uses. Therefore until/if a patch is released
we need to pin rake to an older version in Gemfile:

  gem 'rake', '< 11.0'

Then:

  bundle exec rake install

https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11